markdown: rdiscount
permalink: /:title/
url: http://xuezhiyuanlin.github.io
name: xuezhiyuanlin
author: xuezhiyuanlin
qq: 317789135 
email: xuezhiyuanlin@163.com
duoshuo: 雪之苑林001
cnzz: 
weibo: 2418621275
github: xuezhiyuanlin
# pygments: true
safe: true
paginate: 20
about: "这是本人的第一个博客，大家来捧场！！！"
